### ISSUE TITLE
pingjie的定义

### ISSUE THREAD

**Issue by Zac1ary** [Guanyuansheng/TFGAN-PLC#6]

**Comment by Guanyuansheng** [comment]
拼接函数的作用是将分帧后的语音段重组回完整的语音sig





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Guanyuansheng/TFGAN-PLC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月19日(星期二) 下午2:09
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Guanyuansheng/TFGAN-PLC] pingjie的定义 (Issue #6)





 
您好我最近才接触这方面的东西，想问一下您trainer中定义的函数pingjie具体目标是什么呢，最后返回值代表什么意思呢？谢谢！！！
